server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: marluse-backend

    datasource:
      url: jdbc:mysql://localhost:3306/marluse?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: miguel2007$
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MySQLDialect


app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # 24 horas em milissegundos

logging:
  level:
    com.marluse: DEBUG
    org.flywaydb: INFO